[theme]
base = "dark"
primaryColor = "#A78BFA"
backgroundColor = "#0A0908"
secondaryBackgroundColor = "#141019"
textColor = "#F3F4F6"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
